### ISSUE TITLE
add database entry to setup script

### ISSUE THREAD

**Issue by mosqueteiro** [mosqueteiro/detecting_trafficlights#29]
### pre-requirements:
* [x] git clone `project`
* [x] EBS volume with dataset mounted to project git folder #26 
* [x] docker environment built with pyscopg2 #25 

### Tasks:
* [x] check database structure is correct
* [x] change _segmentation_ type to `BYTEA` in initdb.sql
* [x] add `BYTEA` *seg_dims* to imgaes table in initdb.sql
* [x] change _bbox_ to `BYTEA` in initdb.sql
* [x] update `BuildDatabase`:
   * [x] `build_sql` don't need `create_tables` anymore...
   * [x] `load_json` change "_segmentation_" to bytestring
   * [x] `load_json` make "*seg_dims*" to bytestring
   * [x] `load_json` change "_bbox_" to bytestring
* [x] update `QueryDatabase`:
   * [x] read _segmentation_ from bytestring
   * [x] read *seg_dims* from bytestring reshape _segmentation_
   * [x] read _bbox_ from bytestring
* [ ] run `get_images` on small query table to make sure file pathing setup correctly (no downloading)
* [ ] update `data_pipline.py` to use _argparse_ in `"__main__"` to load annotations
* [ ] add bash command to setup script to load appropriate _dataset+annotations_

**Comment by mosqueteiro** [comment]
**AUDIBLE:** going to store sementation as json string to preserve different structures. We won't be using this during current experiments anyways.

* [x] change _segmentation_ type to `JSON`
* [x] remove *seg_dims*
* [x] check number of colunms (7)
* `BuildDatabase`:
   * [x] pop `info` into `self.info`
   * [x] convert tables to DataFrames
   * [x] update `bbox` conversions to bytestring
   * [x] update `segmentation` conversions to json string
   * [x] write tables to .csv (s) and compare sum of sizes to json size
* `QueryDatabase`:
  * [x] remove read *seg_dims*
  * [x] update read _segmentation_
* [ ] **?** move csv(s) to `docker/postgres` then:
   * [ ] update postgres `Dockerfile` to copy csv(s) into db

**Comment by mosqueteiro** [comment]
> **AUDIBLE:** going to store sementation as json string to preserve different structures. We won't be using this during current experiments anyways.
> ....
> 

possible issue with index of pandas DF, use `set_index('column')`

**Comment by mosqueteiro** [comment]
finally have models training again
